### ISSUE TITLE
Exception in Tkinter callback

### ISSUE THREAD

**Issue by CheemaOTB** [Proxlight/Proxlight-Designer#1]
When I click the create button i get this error

```python 
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1885, in __call__
    return self.func(*args)
  File "C:\Users\Owner\Desktop\Proxlight-Designer\Proxlight Designer.py", line 24, in btn_clicked
    elif not output_path:
NameError: name 'output_path' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1885, in __call__
    return self.func(*args)
  File "C:\Users\Owner\Desktop\Proxlight-Designer\Proxlight Designer.py", line 29, in btn_clicked
    backend.generate_code(token,URL, output_path)
  File "C:\Users\Owner\Desktop\Proxlight-Designer\backend.py", line 86, in generate_code
    data = response.json()
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python39\lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python39\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python39\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by CheemaOTB** [comment]
It was a issue in my code
